"""Generate a constant, synthesizable ROM. No runtime files are needed by FPGA."""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
BANK = ROOT / "src/design/word_engine/word_bank.txt"
ROM = BANK.with_name("word_rom.sv")


def render():
    words = BANK.read_text(encoding="ascii").splitlines()
    if len(words) != 50 or len(set(words)) != 50:
        raise ValueError("The current six-bit selector requires exactly 50 distinct words")
    if any(re.fullmatch(r"[A-Z]{4,12}", word) is None for word in words):
        raise ValueError("Each word must have 4..12 uppercase ASCII letters")
    if not any(len(word) >= 6 for word in words):
        raise ValueError("Hard mode requires at least one word with 6 or more letters")
    lines = [
        "`timescale 1ns/1ps",
        "// Generated by scripts/generate_word_rom.py from word_bank.txt.",
        "// Character 0 is word_data[7:0]; unused bytes are ASCII spaces.",
        "// Constant case ROM: Vivado may implement it using LUTs.",
        "module word_rom (",
        "    input  logic [5:0]  index,",
        "    output logic [95:0] word_data,",
        "    output logic [3:0]  word_length,",
        "    output logic        valid",
        ");",
        "    always_comb begin",
        "        word_data = {12{8'h20}};",
        "        word_length = 4'd0;",
        "        valid = 1'b1;",
        "        case (index)",
    ]
    for index, word in enumerate(words):
        packed = int.from_bytes(word.ljust(12).encode("ascii"), "little")
        lines.append(f"            6'd{index}: begin word_data = 96'h{packed:024X}; "
                     f"word_length = 4'd{len(word)}; end // {word}")
    lines += ["            default: valid = 1'b0;", "        endcase", "    end", "endmodule", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify without rewriting RTL")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not ROM.exists() or ROM.read_text(encoding="ascii") != expected:
            raise SystemExit("FAIL: word_rom.sv is not synchronized with word_bank.txt")
        print("PASS: 50 valid distinct words; RTL matches the bank")
    else:
        ROM.write_text(expected, encoding="ascii")
        print(f"Generated {ROM}")
